appname: GeoPaper
mysql:
  datasource: root:WQAOIaiona8X@tcp(202.114.205.43:33069)/geopaper?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
redis:
  addr: 202.114.205.43:63799
  password: WQAOIaiona8X
  db: 0